### ISSUE TITLE
Support Turn Time

### ISSUE THREAD

**Issue by brettbates** [brettbates/pgn_parser#2]
1. a4 {12 that took 12 secs}

Officially there is no PGN idea for clocktime, so different places have implemented different ways.

E.g

{12 This took 12 secs}
{preamble [%clk 0:0:12] took 12 secs}

For now will leave this up to the user to implement timing as it is not part of the pgn spec. Later may look at supporting this as the need arises.

**Comment by Alex-Emmert** [comment]
This would be really helpful - I'm trying to analyze Lichess PGNs and I get an error when I try to parse a game. I believe it's an issue with the clock time brackets after the checkmating move:

```
Traceback (most recent call last):
  File "c:\Users\aremm\Desktop\Chess\Chess.py", line 58, in <module>
    loadGame("game.txt")
  File "c:\Users\aremm\Desktop\Chess\Chess.py", line 21, in loadGame
    game = parser.parse(gameTxt, actions=pgn.Actions())
  File "C:\Users\aremm\AppData\Roaming\Python\Python37\site-packages\pgn_parser\parser.py", line 1604, in parse
    return parser.parse()
  File "C:\Users\aremm\AppData\Roaming\Python\Python37\site-packages\pgn_parser\parser.py", line 1588, in parse
    raise ParseError(format_error(self._input, self._failure, self._expected))
pgn_parser.parser.ParseError: Line 21: expected "(", [\s], [0-9], "1-0", "0-1", "1/2-1/2", "*", [\s]
1. d4 { [%clk 0:03:00] } Nc6 { [%clk 0:03:00] } { A40 Mikenas Defense } 2. Nf3 { [%clk 0:02:56] } e5 { [%clk 0:02:58] } 3. d5 { [%clk 0:02:54] } Nd4 { [%clk 0:02:55] 
} 4. e3 { [%clk 0:02:52] } Nxf3+ { [%clk 0:02:53] } 5. Qxf3 { [%clk 0:02:50] } Nf6 { [%clk 0:02:51] } 6. Nc3 { [%clk 0:02:47] } Bb4 { [%clk 0:02:46] } 7. e4 { [%clk 0:02:44] } d6 { [%clk 0:02:38] } 8. Bg5 { [%clk 0:02:43] } h6 { [%clk 0:02:33] } 9. Bxf6 { [%clk 0:02:38] } gxf6 { [%clk 0:02:33] } 10. Bb5+ { [%clk 0:02:35] } c6 { [%clk 0:02:31] } 11. dxc6 { [%clk 0:02:34] } Bxc3+ { [%clk 0:02:24] } 12. Qxc3 { [%clk 0:02:31] } bxc6 { [%clk 0:02:22] } 13. Bxc6+ { [%clk 0:02:25] } Bd7 { [%clk 0:02:20] } 14. Bxa8 { [%clk 0:02:17] } Qxa8 { [%clk 0:02:19] } 15. O-O { [%clk 0:02:13] } Qxe4 { [%clk 0:02:17] } 16. Rfe1 { [%clk 0:02:11] } Qg6 { [%clk 0:02:09] } 17. Rad1 { [%clk 0:02:06] } Ke7 { [%clk 0:02:03] } 18. Qb4 { [%clk 0:02:01] } Bh3 { [%clk 0:01:59] } 19. g3 { [%clk 0:01:59] } Qxc2 { [%clk 0:01:53] } 20. Qxd6+ { [%clk 0:01:54] } Ke8 { [%clk 0:01:51] } 21. Qd8# { [%clk 0:01:52] } { White wins by checkmate. } 1-0
```

I don't personally need the clocktime info, so a command to simply remove the clocktime annotations would be appreciated as well.

Thank you so much for creating this library, it's a huge help to me!
